Repository Holmusk/three-layer, pull requests merged in 2018-05, with the labels that each got.

#1 Use universum instead of protolude, add hlint files
  .hlint-universum.yaml
  .hlint.yaml
  README.md
  app/Main.hs
  package.yaml
  src/Lib.hs
  src/Lib/App.hs
  src/Lib/App/Env.hs
  src/Lib/App/Error.hs
  src/Lib/Effects/Session.hs
  src/Lib/Effects/User.hs
  src/Lib/Server/Auth.hs
  src/Lib/Util/App.hs
  src/Lib/Util/JWT.hs
  src/Lib/Util/Password.hs
  src/Prelude.hs
  stack.yaml
  test/AuthSpec.hs
  test/JWTSpec.hs
  three-layer.cabal
Labels: enhancement

#3 Switch to hedgehog
  package.yaml
  test/JWTSpec.hs
  three-layer.cabal
Labels: tests

#5 Use HashMap instead os Map in AppEnv
  README.md
  package.yaml
  src/Lib.hs
  src/Lib/App/Env.hs
  src/Lib/Effects/Session.hs
  src/Lib/Util/App.hs
  test/AuthSpec.hs
  three-layer.cabal
Labels: refactoring

#11 [#6] Wrap Password stuff into newtypes
  package.yaml
  src/Lib/Effects/Session.hs
  src/Lib/Effects/User.hs
  src/Lib/Server/Auth.hs
  src/Lib/Util/App.hs
  src/Lib/Util/JWT.hs
  src/Lib/Util/Password.hs
  test/AuthSpec.hs
  three-layer.cabal
Labels: refactoring

#12 [#9] Use servant-generic
  package.yaml
  src/Lib/Server.hs
  src/Lib/Server/Auth.hs
  three-layer.cabal
Labels: library, refactoring

#15 [#8] Fix warnings
  .gitignore
  package.yaml
  src/Lib/Effects/User.hs
  src/Lib/Server.hs
  src/Lib/Server/Auth.hs
  src/Lib/Util/App.hs
  src/Lib/Util/JWT.hs
  src/Lib/Util/Password.hs
  test/AuthSpec.hs
  three-layer.cabal
Labels: refactoring

#13 [#7] Implement property test for passwords
  .gitignore
  src/Lib/Util/Password.hs
  test/Test/AuthSpec.hs
  test/Test/JWTSpec.hs
  test/Test/Password.hs
Labels: tests

#16 [#14] Add elm types generators
  .gitignore
  generate-elm/Main.hs
  package.yaml
  src/Lib/Effects/User.hs
  src/Lib/Server/Auth.hs
  src/Lib/Util/Password.hs
Labels: enhancement, library

#19 [#18] Change PasswordHash to Text
  src/Lib/Util/Password.hs
  test/Test/AuthSpec.hs
Labels: enhancement, refactoring

#21 [#10] Replace monad-logger with katip
  README.md
  package.yaml
  src/Lib/App.hs
  src/Lib/Server/Auth.hs
  stack.yaml
  test/Test/AuthSpec.hs
Labels: library
