Repository Holmusk/three-layer, pull requests merged in 2019-07, with the labels that each got.

#71 [#70] Fix failsWith function
  test/Test/Assert.hs
Labels: tests

#76 [#72] Update multiple files, clean up
  .gitignore
  .stylish-haskell.yaml
  sql/schema.sql
  src/Lib.hs
  src/Lib/App/Env.hs
  src/Lib/Core/Admin.hs
  src/Lib/Core/Email.hs
  src/Lib/Core/Jwt.hs
  src/Lib/Core/Password.hs
  src/Lib/Core/Session.hs
  src/Lib/Core/User.hs
  src/Lib/Db/User.hs
  src/Lib/Effects/Jwt.hs
  src/Lib/Effects/Measure.hs
  src/Lib/Server.hs
  src/Lib/Server/Auth.hs
  src/Lib/Server/Types.hs
Labels: refactoring

#77 [#75] Integrate postgresql-simple-named library
  src/Lib/App/Error.hs
  src/Lib/Db/Functions.hs
  src/Lib/Db/User.hs
  src/Prelude.hs
  stack.yaml
  three-layer.cabal
Labels: enhancement, library
