Repository Holmusk/three-layer, pull requests merged in 2019-05, with the labels that each got.

#57 [#56] Bump up to 8.6.5, clean up a bit
  .circleci/circle.yml
  .circleci/config.yml
  .gitignore
  .hlint-relude.yaml
  Dockerfile
  LICENSE
  Setup.hs
  circle.yml
  fix-point/LICENSE
  fix-point/app/Main.hs
  fix-point/fix-point.cabal
  fix-point/stack.yaml
  package.yaml
  src/Lib.hs
  src/Lib/App/Env.hs
  src/Lib/App/Error.hs
  src/Lib/App/Monad.hs
  src/Lib/Core/Jwt.hs
  src/Lib/Effects/Jwt.hs
  src/Lib/Effects/Log.hs
  src/Lib/Server.hs
  src/Lib/Server/Auth.hs
  src/Lib/Time.hs
  src/Prelude.hs
  stack.yaml
  test/Test/Auth.hs
  test/Test/Core/Jwt.hs
  three-layer.cabal
Labels: enhancement, refactoring

#60 [#50] Move to elm-street, clean imports
  frontend/src/Lib/Core/Decoder.elm
  frontend/src/Lib/Core/ElmStreet.elm
  frontend/src/Lib/Core/Encoder.elm
  frontend/src/Lib/Core/Types.elm
  generate-elm/Main.hs
  src/Lib/Core/Admin.hs
  src/Lib/Core/Email.hs
  src/Lib/Core/Id.hs
  src/Lib/Core/Jwt.hs
  src/Lib/Core/Password.hs
  src/Lib/Core/User.hs
  src/Lib/Effects/User.hs
  src/Lib/Server/Auth.hs
  src/Prelude.hs
  stack.yaml
  test/Test/Auth.hs
  test/Test/Core/Jwt.hs
  test/Test/Core/Password.hs
  three-layer.cabal
Labels: library, refactoring

#62 [#58] Switch to better SQL integration
  .circleci/config.yml
  Makefile
  sql/drop.sql
  sql/schema.sql
  sql/seed.sql
  src/Lib.hs
  src/Lib/App/Env.hs
  src/Lib/App/Error.hs
  src/Lib/Core/Password.hs
  src/Lib/Db.hs
  src/Lib/Db/Functions.hs
  src/Lib/Db/Schema.hs
  src/Lib/Db/User.hs
  src/Lib/Effects/User.hs
  src/Lib/Server/Auth.hs
  stack.yaml
  test/Spec.hs
  test/Test/Assert.hs
  test/Test/Auth.hs
  test/Test/Common.hs
  test/Test/Core/Jwt.hs
  test/Test/Core/Password.hs
  three-layer.cabal
Labels: library, refactoring

#63 [#47] Rewrite readme
  README.md
Labels: docs

#65 [#59] Introduce TOML config
  config.toml
  src/Lib.hs
  src/Lib/Config.hs
  src/Lib/Db/Functions.hs
  stack.yaml
  test/Spec.hs
  three-layer.cabal
Labels: config

#64 [#17] Consider using 'clock' package instead of 'getCPUTime'
  src/Lib/Effects/Measure.hs
  three-layer.cabal
Labels: library
